//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStoreManagement.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedBill
    {
        public string detailedBillId { get; set; }
        public string billId { get; set; }
        public string detailedShoesId { get; set; }
        public string shoesName { get; set; }
        public Nullable<double> shoesCost { get; set; }
        public Nullable<int> shoesOrderedAmount { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual DetailedSho DetailedSho { get; set; }
    }
}
