//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStoreManagement.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sho()
        {
            this.DetailedShoes = new HashSet<DetailedSho>();
        }
    
        public string shoesId { get; set; }
        public string shoesName { get; set; }
        public string shoesDescription { get; set; }
        public Nullable<double> shoesCost { get; set; }
        public string shoesTypeId { get; set; }
        public string shoesBrand { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailedSho> DetailedShoes { get; set; }
        public virtual ShoesType ShoesType { get; set; }
    }
}
