//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStoreManagement.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public string staffId { get; set; }
        public string staffCMND { get; set; }
        public Nullable<bool> staffGender { get; set; }
        public string staffName { get; set; }
        public string staffTelephoneNumber { get; set; }
        public string staffAddress { get; set; }
        public Nullable<System.DateTime> staffBirthday { get; set; }
        public string staffEmail { get; set; }
        public string staffRole { get; set; }
        public Nullable<int> staffStateId { get; set; }
        public Nullable<System.DateTime> staffStartDate { get; set; }
        public Nullable<System.DateTime> staffEndDate { get; set; }
        public string accountId { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual StaffState StaffState { get; set; }
    }
}
